# Generated by Django 3.1.6 on 2021-02-14 02:20

import authentications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_auto_20210213_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='user/null.png', null=True, upload_to=authentications.models.user_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
