# Generated by Django 3.1.6 on 2021-02-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0005_auto_20210214_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[(0, 'President'), (1, 'V_President'), (2, 'head'), (3, 'Special Committee'), (4, 'Member')], max_length=20),
        ),
    ]
