# Generated by Django 3.1.6 on 2021-02-14 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_auto_20210214_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('PRESIDENT', 'President'), ('V_PRESIDENT', 'V President'), ('HEAD', 'Head'), ('SPECIAL_COMMITTEE', 'Special Committee'), ('MEMBER', 'Member')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.role', verbose_name='Role'),
        ),
    ]
