# Generated by Django 3.1.6 on 2021-02-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0008_auto_20210216_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccountsLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(default='https://www.csec-astu.tech?*Defautl*', verbose_name='Website')),
                ('github', models.URLField(default='https://www.github.com?*Defautl*', verbose_name='Github')),
                ('twitter', models.URLField(default='https://www.twitter.com?*Defautl*', verbose_name='Twitter')),
                ('kattis', models.URLField(default='https://open.kattis.com?*Defautl*', verbose_name='Kattis')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='socials',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.socialaccountslinks', verbose_name='SocialAccountsLinks'),
        ),
    ]
