# Generated by Django 3.1.6 on 2021-02-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0010_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='+251911111111', max_length=50, null=True, verbose_name='Phone'),
        ),
    ]
