# Generated by Django 3.1.6 on 2021-02-16 09:15

import authentications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0011_auto_20210216_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='users/null.png', null=True, upload_to=authentications.models.user_directory_path, verbose_name='Image'),
        ),
    ]
