# Generated by Django 3.1.6 on 2021-02-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0012_auto_20210216_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccountslinks',
            name='kattis',
        ),
        migrations.AddField(
            model_name='socialaccountslinks',
            name='linkdin',
            field=models.URLField(default='https://linkedin.com/in/?*Defautl*', verbose_name='Linkdin'),
        ),
        migrations.AlterField(
            model_name='socialaccountslinks',
            name='github',
            field=models.URLField(default='https://www.github.com/?*Defautl*', verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='socialaccountslinks',
            name='twitter',
            field=models.URLField(default='https://www.twitter./?*Defautl*', verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='socialaccountslinks',
            name='website',
            field=models.URLField(default='https://www.csec-astu.tech/?*Defautl*', verbose_name='Website'),
        ),
    ]
