# Generated by Django 3.1.6 on 2021-02-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0014_auto_20210216_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccountslinks',
            name='github',
            field=models.URLField(blank=True, default='https://www.github.com/?*Defautl*', null=True, verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='socialaccountslinks',
            name='linkedin',
            field=models.URLField(blank=True, default='https://linkedin.com/in/?*Defautl*', null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='socialaccountslinks',
            name='twitter',
            field=models.URLField(blank=True, default='https://www.twitter./?*Defautl*', null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='socialaccountslinks',
            name='website',
            field=models.URLField(blank=True, default='https://www.csec-astu.tech/?*Defautl*', null=True, verbose_name='Website'),
        ),
    ]
